### ISSUE TITLE
Illegal memory access ?

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [pathak22/context-encoder#6]
I am trying to run your demo (ubuntu 16.04, cuda 8) but something goes wrong in the forward pass.
The line "net=models/inpaintCenter/paris_inpaintCenter.t7 name=paris_result imDir=images/paris overlapPred=4 manualSeed=222 batchSize=21 gpu=1 th demo.lua" gives me the following error.
I haven't changed anything in the code. Could it be GPU memory requirements ? (I have 6GB)
Any help would be hugely appriciated !

net=models/inpaintCenter/paris_inpaintCenter.t7 name=paris_result imDir=images/paris overlapPred=4 manualSeed=222 batchSize=21 gpu=1 th demo.lua
{
  gpu : 1
  net : "models/inpaintCenter/paris_inpaintCenter.t7"
  overlapPred : 4
  manualSeed : 222
  name : "paris_result"
  nc : 3
  imDir : "images/paris"
  batchSize : 21
}
Seed: 222	
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> (16) -> (17) -> output]
  (1): nn.Sequential {
    [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> output]
    (1): nn.SpatialConvolution(3 -> 64, 4x4, 2,2, 1,1)
    (2): nn.LeakyReLU(0.2)
    (3): nn.SpatialConvolution(64 -> 64, 4x4, 2,2, 1,1)
    (4): nn.SpatialBatchNormalization (4D) (64)
    (5): nn.LeakyReLU(0.2)
    (6): nn.SpatialConvolution(64 -> 128, 4x4, 2,2, 1,1)
    (7): nn.SpatialBatchNormalization (4D) (128)
    (8): nn.LeakyReLU(0.2)
    (9): nn.SpatialConvolution(128 -> 256, 4x4, 2,2, 1,1)
    (10): nn.SpatialBatchNormalization (4D) (256)
    (11): nn.LeakyReLU(0.2)
    (12): nn.SpatialConvolution(256 -> 512, 4x4, 2,2, 1,1)
    (13): nn.SpatialBatchNormalization (4D) (512)
    (14): nn.LeakyReLU(0.2)
    (15): nn.SpatialConvolution(512 -> 4000, 4x4)
  }
  (2): nn.SpatialBatchNormalization (4D) (4000)
  (3): nn.LeakyReLU(0.2)
  (4): nn.SpatialFullConvolution(4000 -> 512, 4x4)
  (5): nn.SpatialBatchNormalization (4D) (512)
  (6): nn.ReLU
  (7): nn.SpatialFullConvolution(512 -> 256, 4x4, 2,2, 1,1)
  (8): nn.SpatialBatchNormalization (4D) (256)
  (9): nn.ReLU
  (10): nn.SpatialFullConvolution(256 -> 128, 4x4, 2,2, 1,1)
  (11): nn.SpatialBatchNormalization (4D) (128)
  (12): nn.ReLU
  (13): nn.SpatialFullConvolution(128 -> 64, 4x4, 2,2, 1,1)
  (14): nn.SpatialBatchNormalization (4D) (64)
  (15): nn.ReLU
  (16): nn.SpatialFullConvolution(64 -> 3, 4x4, 2,2, 1,1)
  (17): nn.Tanh
}
Loaded Image Block: 	21 x 3 x 128 x 128	
/home/user/torch/install/bin/luajit: /home/user/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 6 module of nn.Sequential:
/home/user/torch/install/share/lua/5.1/nn/THNN.lua:110: bad argument #2 to 'v' (3D or 4D (batch mode) tensor is expected at /home/user/torch/extra/cunn/lib/THCUNN/SpatialConvolutionMM.cu:12)
stack traceback:
	[C]: in function 'v'
	/home/user/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
	...er/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:79: in function <...er/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:76>
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/user/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/user/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/user/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	demo.lua:68: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/user/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/user/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	demo.lua:68: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50
THCudaCheck FAIL file=/home/user/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=147 error=77 : an illegal memory access was encountered

**Comment by ThibaultGROUEIX** [comment]
I tried it on another computer and it worked. must be something wrong with my torch install. I'm closing the thread.

**Comment by ThibaultGROUEIX** [comment]
I guess i had an outdated version of cunn.
luarocks install cutorch
luarocks install cunn solved it.
